### ISSUE TITLE
Spawn building in Sky View

### ISSUE THREAD

**Issue by mondobe** [mondobe/TetraCity#1]
For you, Mike, I'll do a user story...

As a player, I want to click my mouse in the Sky View (accessible by pressing TAB) and spawn the sprite of a random building, with no further functionality at the moment.

- Create a node with a script that detects mouse clicks
- When a mouse click is detected, make sure you're in Sky View (add the MovingCamera node as an `@export`)
- If you are indeed in Sky View, choose a building randomly from a list of `BuildingBlueprint` resources
- Add a `Sprite2D` node as the child of the earlier node, move it to the mouse cursor, and change its texture to the one used by the `BuildingBlueprint`

**Comment by MellifiedRadishes** [comment]
#2 Will complete this issue.
