### ISSUE TITLE
Create Settings screen

### ISSUE THREAD

**Issue by mondobe** [mondobe/TetraCity#21]
As a user, I want to update the game's settings in a central place to optimize my experience

## Design

- The settings screen should have a "Settings" header and contain some UI for controlling various aspects of the game
- The settings screen should have a button to return to the title screen

## Implementation

- The settings screen should be its own standalone scene
- All UI elements should use nodes in the `Control` family, and everything else should use nodes in the `Node2D` family
- For now, just use some placeholder settings. They don't have to do anything.
- The UI should use a `ScrollContainer` or similar node to be scrollable, containing a `VBox` that holds the actual controls
- All settings should be labeled
- Don't worry about art right now. Basic is good.

**Comment by Peeda** [comment]
#28 Settings scene just dropped
